# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:15
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoPatron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoAsosiacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoIdentificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=30)),
                ('correcto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ElementoOpcionMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=30)),
                ('correcta', models.CharField(max_length=30)),
                ('incorrecta1', models.CharField(max_length=30)),
                ('incorrecta2', models.CharField(max_length=30)),
                ('incorrecta3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoOrdenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=30)),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ElementoVoF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=30)),
                ('verdad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('problemas', ckeditor.fields.RichTextField()),
                ('solucion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Asociacion',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoa.Actividad')),
                ('enunGeneral', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
            bases=('adoa.actividad',),
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoa.Actividad')),
                ('enunGeneral', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
            bases=('adoa.actividad',),
        ),
        migrations.CreateModel(
            name='OpcionMultiple',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoa.Actividad')),
                ('enunGeneral', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
            bases=('adoa.actividad',),
        ),
        migrations.CreateModel(
            name='Ordenamiento',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoa.Actividad')),
                ('enunGeneral', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
            bases=('adoa.actividad',),
        ),
        migrations.CreateModel(
            name='VerdaderoFalso',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoa.Actividad')),
                ('enunGeneral', models.CharField(max_length=30)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
            bases=('adoa.actividad',),
        ),
        migrations.AddField(
            model_name='objetoaprendizaje',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.Patron'),
        ),
        migrations.AddField(
            model_name='objetoaprendizaje',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contenidopatron',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.Patron'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='objetoAprendizaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.ObjetoAprendizaje'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='objetoAprendizaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.ObjetoAprendizaje'),
        ),
        migrations.AddField(
            model_name='elementovof',
            name='VoF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.VerdaderoFalso'),
        ),
        migrations.AddField(
            model_name='elementoordenamiento',
            name='ordenamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.Ordenamiento'),
        ),
        migrations.AddField(
            model_name='elementoopcionmultiple',
            name='multiple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.OpcionMultiple'),
        ),
        migrations.AddField(
            model_name='elementoidentificacion',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.Identificacion'),
        ),
        migrations.AddField(
            model_name='elementoasosiacion',
            name='asociacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.Asociacion'),
        ),
    ]
