# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 23:20
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', ckeditor.fields.RichTextField()),
                ('tipo', models.CharField(choices=[('0', 'VerdaderoFalso'), ('1', 'Ordenamiento'), ('2', 'OpcionMultiple'), ('3', 'Identificacion'), ('4', 'Asociacion')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('titulo', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoPatron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('titulo', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ElementoAsosiacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(upload_to=b'')),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoa.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoIdentificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', ckeditor.fields.RichTextField()),
                ('correcto', models.BooleanField()),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoa.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoOpcionMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', ckeditor.fields.RichTextField()),
                ('correcta', ckeditor.fields.RichTextField()),
                ('incorrecta1', ckeditor.fields.RichTextField()),
                ('incorrecta2', ckeditor.fields.RichTextField()),
                ('incorrecta3', ckeditor.fields.RichTextField()),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoa.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoOrdenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', ckeditor.fields.RichTextField()),
                ('orden', models.IntegerField()),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoa.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoVoF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', ckeditor.fields.RichTextField()),
                ('verdad', models.BooleanField()),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoa.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('problemas', ckeditor.fields.RichTextField()),
                ('solucion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='objetoaprendizaje',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.Patron'),
        ),
        migrations.AddField(
            model_name='objetoaprendizaje',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contenidopatron',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.Patron'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='objetoAprendizaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.ObjetoAprendizaje'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='objetoAprendizaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoa.ObjetoAprendizaje'),
        ),
    ]
