# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 04:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='titulo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='asociacion',
            name='enunGeneral',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='titulo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contenidopatron',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contenidopatron',
            name='titulo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='elementoasosiacion',
            name='enunciado',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='elementoidentificacion',
            name='enunciado',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='elementoopcionmultiple',
            name='correcta',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='elementoopcionmultiple',
            name='enunciado',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='elementoopcionmultiple',
            name='incorrecta1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='elementoopcionmultiple',
            name='incorrecta2',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='elementoopcionmultiple',
            name='incorrecta3',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='elementoordenamiento',
            name='enunciado',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='elementovof',
            name='enunciado',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='enunGeneral',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='objetoaprendizaje',
            name='titulo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='opcionmultiple',
            name='enunGeneral',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ordenamiento',
            name='enunGeneral',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='patron',
            name='titulo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='verdaderofalso',
            name='enunGeneral',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
